// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6OtjKKthntObeVpO31A9dZPRoTiLprHM',
    appId: '1:373730537373:web:dd8ac89b1d54485feb8974',
    messagingSenderId: '373730537373',
    projectId: 'iconicapp-447005',
    authDomain: 'iconicapp-447005.firebaseapp.com',
    storageBucket: 'iconicapp-447005.firebasestorage.app',
    measurementId: 'G-5H0E00EMBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhSFzN2-FmYOSJn7P86bewYUoyDxdWNAU',
    appId: '1:373730537373:android:8b3964b23b742be5eb8974',
    messagingSenderId: '373730537373',
    projectId: 'iconicapp-447005',
    storageBucket: 'iconicapp-447005.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6SCIVuIUfI19IyWxFaRZe0oOs_a9-A9Q',
    appId: '1:373730537373:ios:09e1e902c0a8e5f5eb8974',
    messagingSenderId: '373730537373',
    projectId: 'iconicapp-447005',
    storageBucket: 'iconicapp-447005.firebasestorage.app',
    iosBundleId: 'com.pranikah.praNikahApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6SCIVuIUfI19IyWxFaRZe0oOs_a9-A9Q',
    appId: '1:373730537373:ios:09e1e902c0a8e5f5eb8974',
    messagingSenderId: '373730537373',
    projectId: 'iconicapp-447005',
    storageBucket: 'iconicapp-447005.firebasestorage.app',
    iosBundleId: 'com.pranikah.praNikahApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6OtjKKthntObeVpO31A9dZPRoTiLprHM',
    appId: '1:373730537373:web:7e4518a0eb0f4e43eb8974',
    messagingSenderId: '373730537373',
    projectId: 'iconicapp-447005',
    authDomain: 'iconicapp-447005.firebaseapp.com',
    storageBucket: 'iconicapp-447005.firebasestorage.app',
    measurementId: 'G-W7MB83BM2Y',
  );
}
